server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  instance:
    hostname: localhost
    instance-id: payment8001
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
